### ISSUE TITLE
startpartial / endpartial does not follow convention according to PyCharm

### ISSUE THREAD

**Issue by jmuncaster** [carltongibson/django-template-partials#12]
![CleanShot 2023-07-26 at 10 58 11@2x](https://github.com/carltongibson/django-template-partials/assets/2768145/b03557af-b65b-422c-8537-5fb19ba2f160)

Would it make more sense to define a partial with `{% partial %} / {% endpartial %}` to be consistent with other blocks?

And include the partial with something like `{% include-partial %}`?

I know it's a big deal to request a change of keywords, but it seems this would at least be consistent with what one IDE is expecting. Indeed, `{% if %} / {% endif %}` and `{% block %} / {% endblock %}` work this way. Or perhaps a user option to choose the start/end tags?

**Comment by carltongibson** [comment]
Hi @jmuncaster — Yes. Hmm. 🤔

Grrr. I liked the syntax, so my initial reaction is along the lines of _not my problem_ — but OK, let's think about it 😅

> And include the partial with something like `{% include-partial %}`?

That really turns me off. Can we come up with something better? (Maybe for the block tag pair? 🤔) _Naming_ as ever. 

PyCharm's behaviour doesn't happen to be tweak-able does it?

**Comment by carltongibson** [comment]
Maybe `partialdef` and `endpartialdef` would be OK? 

Any other ideas?

**Comment by jmuncaster** [comment]
Totally understand the initial reaction :-)

I couldn't find a way to tweak PyCharm behavior other than to disable the check altogether. But PyCharm aside I don't think startX / endX is idiomatic, at least from what I've seen.

I think `partialdef`/`endpartialdef` would be great. I can't think of anything better. I think it is more idiomatic than `partial`/`endpartial` and the existing `startpartial` / `endpartial`.

**Comment by scriptogre** [comment]
I just found out about this library from BugBytes, and I was so happy because so far:

- I've tried django-components - yet it was too verbosey and cluttering my templates
- I've tried slippers - but the {% #button %} {% /button %} syntax really pissed off my IDE (PyCharm) 
I haven't found any tweak to make PyCharm stop complaining for slippers, short of giving up all support for Django templates (unreasonable solution), so I gave up.

I was glad to find this library, which seemed to be exactly what I was looking for. 

But I got the same issue as the @jmuncaster . Please do care about us, PyCharm peasants, and try to fix this issue. I've been waiting for this library for almost a year 😦

I understand the turn off... But there must be a clean enough approach to make everyone happy.
I vouch for:
    Define: {% partialdef %} ... {% endpartialdef %}
    Use: {% partial %}

    Define: {% partialblock %} ... {% endpartialblock %}
    Use: {% partial %}

    Define: {% partialcontent %} ... {% endpartialcontent %}
    Use: {% partial %}

And even this one does not seem SO bad.

    Define: {% partial %} ... {% endpartial %}
    Use: {% includepartial %}

**Comment by carltongibson** [comment]
@scriptogre I'm likely to do something here. 

I just need a window to get it done. (Life..., but that's a separate topic.)

A PR changing the tags to `partialdef`, as per the discussion, plus aliasing the existing `startpartial`, and raising a depreciation warning, would help.

**Comment by scriptogre** [comment]
Hey Carlton! Sorry for the delay :). Had some life going on as well. Hope this is good enough! Let me know if you find any issues.

**Comment by carltongibson** [comment]
Hey @scriptogre -- no worries at all, this is the way 😅

I had an initial glance. It looks lovely. I'm just occupied elsewhere, and then will be swinging back here to put together an update. 🤹‍♀️

**Comment by carltongibson** [comment]
Fixed in 4c3c9cdb0984670beab032162856f8cf73fcdde2
