### ISSUE TITLE
Problem with nesting partials 

### ISSUE THREAD

**Issue by Elweday** [carltongibson/django-template-partials#15]
it doesn't say in the documentations whether it supports it or not but I tried it and it didn't work

**Comment by carltongibson** [comment]
Hi @Elweday. A minimal example is always helpful in an report. 

It might not be something that's feasible, since the node list would need to be recursive.

**Comment by firdaus-aziz** [comment]
![Screenshot from 2023-08-24 12-46-03](https://github.com/carltongibson/django-template-partials/assets/1595757/ac9bb0b0-341e-454d-b2f0-76cda24cdf5c)

Nesting works 👍🏽 

My views:
```
def partial_blue(request):
    if request.htmx.target == "inner":
        return render(request, "flowbite/partial-blue.html#inner")
    if request.htmx.target == "middle":
        return render(request, "flowbite/partial-blue.html#middle")
    if request.htmx.target == "outer":
        return render(request, "flowbite/partial-blue.html#outer")

    return render(request, "flowbite/partial-blue.html")


def partial_red(request):
    if request.htmx.target == "inner":
        return render(request, "flowbite/partial-red.html#inner")
    if request.htmx.target == "middle":
        return render(request, "flowbite/partial-red.html#middle")
    if request.htmx.target == "outer":
        return render(request, "flowbite/partial-red.html#outer")

    return render(request, "flowbite/partial-red.html")
```
My template
```
{% block main %}
... content
{% partial outer %}
...content
{% endblock %}

{% startpartial outer %}
... content
{% partial middle %}
...content
{% endpartial %}

{% startpartial middle %}
... content
{% partial inner %}
...content
{% endpartial %}

{% startpartial inner %}
...content
{% endpartial %}
```

**Comment by carltongibson** [comment]
Thanks @firdaus-aziz, glad you're liking it 😊

**Comment by geoffrey-eisenbarth** [comment]
So would it be correct to say that this library won't support rendering partials that are defined in parent templates?

Given the following templates:

```
# base.html
<html>
  <body>
    <header>
      <nav aria-label="Primary navigation">[...]</nav>
    </header>
    {% partialdef main inline=True %}
    {% block main %}
    <main>[...]</main>
    {% endblock main %}
    {% endpartialdef %}
  </body>
</html>
```

```
# home.html
{% extends 'base.html' %}
{% block main %}
<main>
  <div class="col" aria-label="Sidebar navigation">
    [...]
  </div>
  <div class="col" aria-label="Content">
    {% partialdef content inline=True %}
    [...]
    {% endpartialdef %}
</main>
{% endblock %}
```

my attempts to render `home.html#main` throw a `TemplateDoesNotExist` error.

**Comment by carltongibson** [comment]
Hi @geoffrey-eisenbarth. 

Yes... I see what you're trying to do, and you're right it won't work. Partials are available on the template they're defined in. 
You can `include` a partial from another template, see the [README example](https://github.com/carltongibson/django-template-partials#via-the-template-loader), but `extends` is another kettle of fish. 

In this case, you can use `hx-select="main"` to grab the bit you need, or parameterise the base template variable, to use a slimmed-down wrapper, but I'd probably suggest you're trying to be overly cute with it. The natural usage here is to grab `home.html#content`—that's what partials are about—rather than making a whole main+sidebar into a partial. _Locality of behaviour_ only goes so far: at a certain you are better off breaking things up to keep them simpler. A separate `include` template for the main element could be used on its own (when setting `template_name`) for example, and would be much more obvious than trying to use a partial defined in a different template (which doesn't seem to fit the idea of _locality of behaviour_ at all, once I've said it out loud 🤔) 

I hope that helps!

**Comment by geoffrey-eisenbarth** [comment]
@carltongibson Thank you for your quick response and all your work on this lib (and Django)!

I agree the example might seem a bit contrived, but the use case is that for 90% of my website, clicking on a link should replace the `<main></main>` element with the "main" partial / block, which is made very easy with the following snippet:

```
def get_template_names(self) -> list:
  if self.request.htmx:
    # NOTE: HX-Target ID must match the partial name
    template_names = [f'{self.template_name}#{self.request.htmx.target}]
  else:
    template_names = super().get_template_names()
  return template_names
```

However, one section of the site, "My Account" loads up a sidebar in `<main></main>` that contains a secondary menu (Profile, Billing, History, etc). The goal being that, clicking on a link in the secondary menu also only needs to load the `home.html#content` partial, not the entire `base.html#main` partial (which includes the secondary menu). It's easy enough to have these sidebar links just replace the `main` partial, but I was hoping for something a bit slicker (although, maybe slickness is in the eye of the beholder).

Thanks again for your time, work, and suggestions.

**Comment by carltongibson** [comment]
@geoffrey-eisenbarth You've got your code in-front of you, but from what you'd said I'd imagine you could have a "your-account.html" that had the side bar and then included the content for the main content (be that a partial or not...) — You'll have to play, but I'd hope that'd be simple enough. 

Have fun! 🤩
