### ISSUE TITLE
Jinja support

### ISSUE THREAD

**Issue by jgillard** [carltongibson/django-template-partials#35]
Firstly thanks for this package! I was eager to try it out having read about this and django-render-blocks and watching your talk, but bumped straight into Jinja support as a blocker. I've spent an hour or so digging into this, but I've never looked under the hood at the differences between DTL and Jinja inside Django before, and we additionally use django-jinja which adds an extra layer of complexity, so I came away not much wiser about what it would take to make this work. I'd be eager to hear about whether this is supported as maybe it's django-jinja getting in my way, or whether this would require future work on this package to support.

**Comment by carltongibson** [comment]
Hi @jgillard. 

`django-template-partials` is just for the Django Template Language. (I'm afraid I'm not a big Jinja user.)

@mikeckennedy has a package for Jinja you can find here: https://github.com/mikeckennedy/jinja_partials

**Comment by kevinrenskers** [comment]
I was in the exact same position, also wanting support specifically for django-jinja, and built this: https://github.com/loopwerk/django-jinja-render-block

It's a bit more limited in scope (it renders a block within a template rather than support reusable template partials), but it does do it via the template name, just like this project.
